# Python Assignment: Data Structures, Functions, Numpy & Pandas

## Section A: Data Structures & Control Structures

### Question 1
Create a list of 5 integers and perform list operations.

In [1]:
# Create a list of 5 integers
numbers = [5, 2, 8, 2, 1]

print("Original list:", numbers)

# append
numbers.append(10)
print("After append:", numbers)

# extend
numbers.extend([7, 9])
print("After extend:", numbers)

# insert
numbers.insert(2, 6)
print("After insert:", numbers)

# remove
numbers.remove(2)
print("After remove:", numbers)

# pop
removed_value = numbers.pop()
print("Popped value:", removed_value)
print("After pop:", numbers)

# index
print("Index of 8:", numbers.index(8))

# count
print("Count of 2:", numbers.count(2))

# sort
numbers.sort()
print("After sort:", numbers)

# reverse
numbers.reverse()
print("After reverse:", numbers)

# clear
numbers.clear()
print("After clear:", numbers)

Original list: [5, 2, 8, 2, 1]
After append: [5, 2, 8, 2, 1, 10]
After extend: [5, 2, 8, 2, 1, 10, 7, 9]
After insert: [5, 2, 6, 8, 2, 1, 10, 7, 9]
After remove: [5, 6, 8, 2, 1, 10, 7, 9]
Popped value: 9
After pop: [5, 6, 8, 2, 1, 10, 7]
Index of 8: 2
Count of 2: 1
After sort: [1, 2, 5, 6, 7, 8, 10]
After reverse: [10, 8, 7, 6, 5, 2, 1]
After clear: []


### Question 2
Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [2]:
# Create a tuple with 3 student names
students = ("John", "Alice", "David")

print("Original tuple:", students)

# Try to change the second name
students[1] = "Sarah"

Original tuple: ('John', 'Alice', 'David')


TypeError: 'tuple' object does not support item assignment

**Explanation:** A tuple is immutable, which means its elements cannot be changed after the tuple is created. Therefore, trying to change the second name results in a TypeError.

### Question 3
Create a set of integers with some duplicate values. Print the set and explain the output.

In [3]:
# Create a set with duplicate values
numbers_set = {1, 2, 3, 2, 4, 3, 5, 1}

print("Set:", numbers_set)

Set: {1, 2, 3, 4, 5}


### Question 4
Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [4]:
# Create a dictionary
student = {
    "name": "John",
    "age": 20,
    "city": "Kochi"
}

# Update the age
student["age"] = 21

# Add a new key 'email'
student["email"] = "john@example.com"

# Print the final dictionary
print("Final dictionary:", student)

Final dictionary: {'name': 'John', 'age': 21, 'city': 'Kochi', 'email': 'john@example.com'}


### Question 5
Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [5]:
# Take age as a variable
age = 20

# Check voting eligibility
if age >= 18:
    print("The person is eligible to vote.")
else:
    print("The person is not eligible to vote.")

The person is eligible to vote.


### Question 6
Given a 'marks' variable, print the grade according to the following conditions:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [6]:
# Given marks
marks = 85

# Check the grade
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

Grade: B


### Question 7
Given a number, check if it is positive, and if it is also even. If not positive, print if it is zero or negative.

In [7]:
# Given number
number = 8

# Check the number
if number > 0:
    if number % 2 == 0:
        print("The number is positive and even.")
    else:
        print("The number is positive but odd.")
elif number == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

The number is positive and even.


## Section B: NumPy

### Question 8
Create a scalar, a 1D array with values 1 to 5, and a 2D array (2x3) with values from 10 to 60 in steps of 10.

In [8]:
import numpy as np

# Scalar
scalar = np.array(5)

# 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])

# 2D array (2x3) with values from 10 to 60
array_2d = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Scalar:")
print(scalar)

print("\n1D Array:")
print(array_1d)

print("\n2D Array:")
print(array_2d)

Scalar:
5

1D Array:
[1 2 3 4 5]

2D Array:
[[10 20 30]
 [40 50 60]]


### Question 9
Generate a 4x4 NumPy array of random integers between 0 and 100 using np.random.randint().

In [9]:
# Generate a 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))

print("4x4 Random Array:")
print(random_array)


4x4 Random Array:
[[ 1  5 65 92]
 [60 68  7 62]
 [ 9 74 86 26]
 [ 6 93 15 77]]


### Question 10
Create a 2D NumPy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [10]:
import pandas as pd

# Create a 3x3 NumPy array
array_3x3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Convert the NumPy array into a Pandas DataFrame
df = pd.DataFrame(array_3x3, columns=["A", "B", "C"])

# Print the DataFrame
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


## Section C: Exploring Pandas

### Question 11
Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'.

Perform the following operations:
- Use .info() and .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill missing values in 'Salary' with the mean
- Remove duplicate rows

In [11]:
# Create a DataFrame manually with 10 rows
data = {
    "Name": [
        "John", "Alice", "David", "Sarah", "Mike",
        "Emma", "Robert", "Lisa", "Daniel", "John"
    ],
    "Age": [
        22, 25, 30, 28, 35,
        24, 32, 27, 29, 22
    ],
    "City": [
        "Kochi", "Mumbai", "Delhi", "Chennai", "Pune",
        "Kochi", "Bangalore", "Mumbai", "Delhi", "Kochi"
    ],
    "Salary": [
        30000, 45000, 50000, None, 55000,
        40000, 60000, None, 48000, 30000
    ]
}

df_pandas = pd.DataFrame(data)

print("Original DataFrame:")
print(df_pandas)

Original DataFrame:
     Name  Age       City   Salary
0    John   22      Kochi  30000.0
1   Alice   25     Mumbai  45000.0
2   David   30      Delhi  50000.0
3   Sarah   28    Chennai      NaN
4    Mike   35       Pune  55000.0
5    Emma   24      Kochi  40000.0
6  Robert   32  Bangalore  60000.0
7    Lisa   27     Mumbai      NaN
8  Daniel   29      Delhi  48000.0
9    John   22      Kochi  30000.0


In [12]:
# Display DataFrame information
print("DataFrame Information:")
df_pandas.info()

# Display descriptive statistics
print("\nDescriptive Statistics:")
print(df_pandas.describe())

DataFrame Information:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     str    
 1   Age     10 non-null     int64  
 2   City    10 non-null     str    
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), str(2)
memory usage: 556.0 bytes

Descriptive Statistics:
             Age        Salary
count  10.000000      8.000000
mean   27.400000  44750.000000
std     4.273952  10911.985547
min    22.000000  30000.000000
25%    24.250000  37500.000000
50%    27.500000  46500.000000
75%    29.750000  51250.000000
max    35.000000  60000.000000


In [13]:
# Select Name and City columns
selected_columns = df_pandas[["Name", "City"]]

print("Selected Name and City columns:")
print(selected_columns)

Selected Name and City columns:
     Name       City
0    John      Kochi
1   Alice     Mumbai
2   David      Delhi
3   Sarah    Chennai
4    Mike       Pune
5    Emma      Kochi
6  Robert  Bangalore
7    Lisa     Mumbai
8  Daniel      Delhi
9    John      Kochi


In [14]:
# Drop the City column
df_without_city = df_pandas.drop("City", axis=1)

print("DataFrame after dropping City:")
print(df_without_city)

DataFrame after dropping City:
     Name  Age   Salary
0    John   22  30000.0
1   Alice   25  45000.0
2   David   30  50000.0
3   Sarah   28      NaN
4    Mike   35  55000.0
5    Emma   24  40000.0
6  Robert   32  60000.0
7    Lisa   27      NaN
8  Daniel   29  48000.0
9    John   22  30000.0


In [15]:
# Calculate the mean salary
salary_mean = df_pandas["Salary"].mean()

# Fill missing Salary values with the mean
df_pandas["Salary"] = df_pandas["Salary"].fillna(salary_mean)

print("Mean Salary:", salary_mean)
print("\nDataFrame after filling missing Salary values:")
print(df_pandas)

Mean Salary: 44750.0

DataFrame after filling missing Salary values:
     Name  Age       City   Salary
0    John   22      Kochi  30000.0
1   Alice   25     Mumbai  45000.0
2   David   30      Delhi  50000.0
3   Sarah   28    Chennai  44750.0
4    Mike   35       Pune  55000.0
5    Emma   24      Kochi  40000.0
6  Robert   32  Bangalore  60000.0
7    Lisa   27     Mumbai  44750.0
8  Daniel   29      Delhi  48000.0
9    John   22      Kochi  30000.0


In [16]:
# Remove duplicate rows
df_no_duplicates = df_pandas.drop_duplicates()

print("DataFrame after removing duplicate rows:")
print(df_no_duplicates)

DataFrame after removing duplicate rows:
     Name  Age       City   Salary
0    John   22      Kochi  30000.0
1   Alice   25     Mumbai  45000.0
2   David   30      Delhi  50000.0
3   Sarah   28    Chennai  44750.0
4    Mike   35       Pune  55000.0
5    Emma   24      Kochi  40000.0
6  Robert   32  Bangalore  60000.0
7    Lisa   27     Mumbai  44750.0
8  Daniel   29      Delhi  48000.0
